version: '3.8'
services:
   frontend:
      build: ./frontend
      container_name: frontend
      ports:
         - 8080:8080
      depends_on:
         - backend

   backend:
      build: ./backend
      container_name: backend
      ports:
         - 3333:3333
      depends_on:
         - db
      environment:
         DB_HOST: db

   db:
      image: postgres
      restart: always
      ports:
         - 5432:5432
      environment:
         POSTGRES_PASSWORD: postpassworddef
         POSTGRES_USER: postgres
         POSTGRES_DB: lei_condominios
      volumes:
         - condominios-data:/var/lib/postgresql/data

volumes:
   condominios-data:
